### ISSUE TITLE
Setup TravisCI

### ISSUE THREAD

**Issue by jmsv** [jmsv/oaty#2]
Need to add CI setup to run tests and stuff

Something like:

```yaml
language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm test
```
